title: SecuCaster
description: SecuCaster Blog
author: SecuCaster
logo: /static/img/avatar.jpg
github: https://github.com/secucaster
about: SecuCaster@gmail.com

baseurl: "https://secuops.dev"
url: "https://secuops.dev"

allowsearch: true

disqus_shortname: secucaster
google_analytics: UA-119955195-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
